[package]
name = "German work time sheet"
version = "0.1"
entrypoint = "lib.typ"
authors = ["Julius Schmitt"]
license = "MIT"
description = "Track your work hours with a simple csv table."
categories = ["report"]

[template]
path = "template"
entrypoint = "lib.typ"
thumbnail = "thumbnail.png"